### ISSUE TITLE
请问有arm版的harbor产出了么

### ISSUE THREAD

**Issue by bainilybi** [goharbor/harbor-arm#1]
请问，是否有arm版的镜像产出和chart呢？谢谢～

**Comment by yuzp1996** [comment]
There is no arm64 Harbor, but it is in preparation. We plan to provide arm64 Harbor in version 2.3

**Comment by yuzp1996** [comment]
If you want to know more details, you can refer to this document

https://docs.google.com/document/d/1VkWMl6-UKg2evHYnTgaccg9xGt77IR1Tvy-OJL5iMzY/edit?usp=sharing

**Comment by morlay** [comment]
@bainilybi 

`v2.2.0` could try with  `ghcr.io/querycap/harbor/*:ec0ba11` 
https://github.com/orgs/querycap/packages?repo_name=harbor

only need to updates images of helm chart

**Comment by bainilybi** [comment]
Thanks for all
