### ISSUE TITLE
How to build harbor arm?

### ISSUE THREAD

**Issue by saodis** [goharbor/harbor-arm#14]
How to build harbor arm? Are there any help documents?

**Comment by Jeremy-boo** [comment]
Sorry, the documentation will not come out until harbor-arm is officially released

**Comment by jpgkudo** [comment]
When will the official version be released?

**Comment by Jeremy-boo** [comment]
> When will the official version be released?

At present, there are several cases of harbor-arm running official automated tests that have failed. After we solve these problems, the first official version will be released. It is expected this weekend

**Comment by saodis** [comment]
Oh, that's great

**Comment by saodis** [comment]
Oh, that's great



 
From: ZhuBo
Date: 2021-11-15 23:57
To: goharbor/harbor-arm
CC: saodis; Author
Subject: Re: [goharbor/harbor-arm] How to build harbor arm? (Issue #14)
When will the official version be released?
At present, there are several cases of harbor-arm running official automated tests that have failed. After we solve these problems, the first official version will be released. It is expected this weekend
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by saodis** [comment]
@Jeremy-boo Why hasn't the official version been released yet?

**Comment by Yikun** [comment]
Any progress on it? Thanks!
