### ISSUE TITLE
ERROR: for harbor-core Cannot start service core: OCI runtime create failed: container_linux.go:318: starting container process caused "chdir to cwd (\"/harbor\") set in config.json failed: permission denied": unknown

### ISSUE THREAD

**Issue by yanghuinnn** [goharbor/harbor-arm#15]
I compiled the offline installation package using source code on the ARM architecture, decompressed the offline installation package, and executed./install, reporting this error
![屏幕截图 2021-11-11 205647](https://user-images.githubusercontent.com/92514704/141301866-0fec1bba-d09a-41aa-a746-8269aafcafa7.png)

**Comment by liuxiaodong100** [comment]
请问，您如何做的 package_offline 包，运行的什么命令。

**Comment by misteruly** [comment]
@yanghuinnn  这个问题你是怎么解决的呢？我也遇到了
