### ISSUE TITLE
notary-server failed to start due to ssl certificate issue

### ISSUE THREAD

**Issue by Jeremy-boo** [goharbor/harbor-arm#16]
// notary-server error info
{"level":"fatal","msg":"unable to set up TLS: Error reading X509 key pair (cert: \"/etc/notary/notary-signer.crt\", key: \"/etc/notary/notary-signer.key\"): tls: failed to find any PEM data in certificate input. Make sure the key is not encrypted.","time":"2021-11-12T02:32:44Z"}

**Comment by wy65701436** [comment]
from the log, it seems that the binary in the notary-server is for the notary-signer, please confirm it. @Jeremy-boo

**Comment by Jeremy-boo** [comment]
Because docker buildx has a cache, the basic image of notary-signer is used when constructing notary-server. Before constructing notary-server, execute the docker buildx prune -f command to solve this problem

**Comment by Jeremy-boo** [comment]
done
