### ISSUE TITLE
Test Case - Push Index By Docker Manifest FAIL

### ISSUE THREAD

**Issue by Jeremy-boo** [goharbor/harbor-arm#17]
Docker image login did not catch exception and return message is: {'username': 'user-1636995248028', 'password': 'Aa123456', 'email': None, 'serveraddress': '147.75.195.254'}
Docker image pull did not catch exception and return message is: {"status":"Pulling from project-1636995248141/ci_test_index","id":"test_tag"}
{"errorDetail":{"message":"no matching manifest for linux/arm64/v8 in the manifest list entries"},"error":"no matching manifest for linux/arm64/v8 in the manifest list entries"}

**Comment by YangJiao0817** [comment]
Fix in this [PR](https://github.com/goharbor/harbor/pull/16088)
