### ISSUE TITLE
Test Case Fail- Push Singularity file With Singularity CLI

### ISSUE THREAD

**Issue by Jeremy-boo** [goharbor/harbor-arm#20]
FATAL:   Couldn't not parse configuration file /usr/local/etc/singularity/singularity.conf: open /usr/local/etc/singularity/singularity.conf: no such file or directory

**Comment by Jeremy-boo** [comment]
done

**Comment by Jeremy-boo** [comment]
Traceback (most recent call last):
  File "/drone/./tests/apitests/python/test_push_sif_by_singularity.py", line 57, in testPushSingularity
    library.singularity.push_singularity_to_harbor("library:", "library/default/", harbor_server, user_name, user_001_password, TestProjects.project_name, self.repo_name, self.tag)
  File "/drone/tests/apitests/python/library/singularity.py", line 23, in push_singularity_to_harbor
    singularity_pull(tmp_sif_file, from_URI+"//"+from_namespace + image+":" + tag)
  File "/drone/tests/apitests/python/library/singularity.py", line 18, in singularity_pull
    ret = base.run_command( [singularity_cmd, "pull", "--allow-unsigned", out_file, from_sif_file] )
  File "/drone/tests/apitests/python/library/base.py", line 161, in run_command
    raise Exception('Error: Exited with error code: %s. Output:%s'% (e.returncode, e.output))
Exception: Error: Exited with error code: 255. Output:Flag --allow-unsigned has been deprecated, pull no longer exits with an error code in case of unsigned image. Now the flag only suppress warning message.
WARNING: No default remote in use, falling back to default library: https://library.sylabs.io
WARNING: No default remote in use, falling back to default keyserver: https://keys.sylabs.io
FATAL:   While pulling library image: error fetching image: image does not exist in the library: library/default/busybox:1.28 (arm64)

FAILED (errors=1)
['/drone/tests/apitests/python/', '/drone/tests/apitests/python/library', '/drone/library', '/drone/harborclient', '/drone/tests/apitests/python', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/usr/lib/python3.9/site-packages', '/usr/lib/python3.9/site-packages/client-1.0.0-py3.9.egg', '/usr/lib/python3.9/site-packages/python_dateutil-2.8.2-py3.9.egg', '/usr/lib/python3.9/site-packages/swagger_client-1.0.0-py3.9.egg', '/usr/lib/python3.9/site-packages/v2_swagger_client-1.0.0-py3.9.egg']
send: b'POST /api/v2.0/users HTTP/1.1\r\nHost: 147.75.195.254\r\nAccept-Encoding: identity\r\nContent-Length: 146\r\nAccept: application/json\r\nContent-Type: application/json\r\nUser-Agent: OpenAPI-Generator/1.0.0/python\r\nAuthorization: Basic YWRtaW46SGFyYm9yMTIzNDU=\r\n\r\n'
send: b'{"email": "realname-1637504636450@harbortest.com", "realname": "realname-1637504636450", "password": "Aa123456", "username": "user-1637504636450"}'
reply: 'HTTP/1.1 201 Created\r\n'
header: Server: nginx
header: Date: Sun, 21 Nov 2021 14:23:56 GMT
header: Content-Length: 0
header: Connection: keep-alive
header: Location: /api/v2.0/users/40
header: Set-Cookie: sid=fc088605ef26eb4903900f8ce45d8c47; Path=/; Secure; HttpOnly; Secure
header: X-Request-Id: c057ef0a-404d-4aeb-93be-dac3102e44ea
header: Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
header: X-Frame-Options: DENY
header: Content-Security-Policy: frame-ancestors 'none'
send: b'POST /api/v2.0/projects HTTP/1.1\r\nHost: 147.75.195.254\r\nAccept-Encoding: identity\r\nContent-Length: 74\r\nAccept: application/json\r\nContent-Type: application/json\r\nUser-Agent: OpenAPI-Generator/1.0.0/python\r\nAuthorization: Basic dXNlci0xNjM3NTA0NjM2NDUwOkFhMTIzNDU2\r\n\r\n'
send: b'{"project_name": "project-1637504636581", "metadata": {"public": "false"}}'
reply: 'HTTP/1.1 201 Created\r\n'
header: Server: nginx
header: Date: Sun, 21 Nov 2021 14:23:56 GMT
header: Content-Length: 0
header: Connection: keep-alive
header: Location: /api/v2.0/projects/39
header: Set-Cookie: sid=45a9ab2a130c0b6301ad6ba5a79ddbc6; Path=/; Secure; HttpOnly; Secure
header: X-Request-Id: f62545fe-c3c4-4d1d-9e9f-b598ac78248b
header: Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
header: X-Frame-Options: DENY
header: Content-Security-Policy: frame-ancestors 'none'
Command:  singularity pull --allow-unsigned busybox111637504635.sif library://library/default/busybox:1.28
Run command error: Command '['singularity', 'pull', '--allow-unsigned', 'busybox111637504635.sif', 'library://library/default/busybox:1.28']' returned non-zero exit status 255.
expected_error_message: None
send: b'DELETE /api/v2.0/users/40 HTTP/1.1\r\nHost: 147.75.195.254\r\nAccept-Encoding: identity\r\nAccept: application/json\r\nUser-Agent: OpenAPI-Generator/1.0.0/python\r\nAuthorization: Basic YWRtaW46SGFyYm9yMTIzNDU=\r\nContent-Type: application/json\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Date: Sun, 21 Nov 2021 14:23:57 GMT
header: Content-Length: 0
header: Connection: keep-alive
header: Set-Cookie: sid=c2345e78ce69409d85f4d5042b478897; Path=/; Secure; HttpOnly; Secure
header: X-Request-Id: 53e82efa-f931-4606-b8a5-4f5dbb3a6a8f
header: Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
header: X-Frame-Options: DENY
header: Content-Security-Policy: frame-ancestors 'none'

**Comment by YangJiao0817** [comment]
Fix in this [PR](https://github.com/goharbor/harbor/pull/16088)
