### ISSUE TITLE
The harbor component notary-server and notary-signer failed to start

### ISSUE THREAD

**Issue by Jeremy-boo** [goharbor/harbor-arm#22]
Notary signer:
![image](https://user-images.githubusercontent.com/41532403/147643552-15d77241-1ff3-4ad4-ab83-4c2547031a4e.png)

Notary server:
![image](https://user-images.githubusercontent.com/41532403/147643570-3db4b1be-806d-4a00-8d15-52814ee359c9.png)

**Comment by wy65701436** [comment]
Close it as fixed.
